[package]
name = "sparql-data-preparation"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = "1"
itertools = "0"
anyhow = "1"
clap = { version = "4", features = ["derive"] }
indicatif = "0"
rayon = "1"
